.nh
.TH "CIRCLECI-MIGRATE" "1" "Jun 2026" "circleci-migrate" "CircleCI Org Migration CLI"

.SH NAME
circleci-migrate-completion-bash - Generate the autocompletion script for bash


.SH SYNOPSIS
\fBcircleci-migrate completion bash\fP


.SH DESCRIPTION
Generate the autocompletion script for the bash shell.

.PP
This script depends on the 'bash-completion' package.
If it is not installed already, you can install it via your OS's package manager.

.PP
To load completions in your current shell session:

.EX
source <(circleci-migrate completion bash)
.EE

.PP
To load completions for every new session, execute once:

.SS Linux:
.EX
circleci-migrate completion bash > /etc/bash_completion.d/circleci-migrate
.EE

.SS macOS:
.EX
circleci-migrate completion bash > $(brew --prefix)/etc/bash_completion.d/circleci-migrate
.EE

.PP
You will need to start a new shell for this setup to take effect.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for bash

.PP
\fB--no-descriptions\fP[=false]
	disable completion descriptions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug logging

.PP
\fB--dest-token\fP=""
	API token for the destination org (env: CIRCLECI_DEST_TOKEN)

.PP
\fB--host\fP="https://circleci.com"
	CircleCI host URL (env: CIRCLECI_HOST)

.PP
\fB--source-token\fP=""
	API token for the source org (env: CIRCLECI_SOURCE_TOKEN)

.PP
\fB--token\fP=""
	Personal API token — fallback for both orgs (env: CIRCLECI_CLI_TOKEN)


.SH SEE ALSO
\fBcircleci-migrate-completion(1)\fP


.SH HISTORY
10-Jun-2026 Auto generated by spf13/cobra
