.nh
.TH "CIRCLECI-MIGRATE" "1" "Jun 2026" "circleci-migrate" "CircleCI Org Migration CLI"

.SH NAME
circleci-migrate-completion-fish - Generate the autocompletion script for fish


.SH SYNOPSIS
\fBcircleci-migrate completion fish [flags]\fP


.SH DESCRIPTION
Generate the autocompletion script for the fish shell.

.PP
To load completions in your current shell session:

.EX
circleci-migrate completion fish | source
.EE

.PP
To load completions for every new session, execute once:

.EX
circleci-migrate completion fish > ~/.config/fish/completions/circleci-migrate.fish
.EE

.PP
You will need to start a new shell for this setup to take effect.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for fish

.PP
\fB--no-descriptions\fP[=false]
	disable completion descriptions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug logging

.PP
\fB--dest-token\fP=""
	API token for the destination org (env: CIRCLECI_DEST_TOKEN)

.PP
\fB--host\fP="https://circleci.com"
	CircleCI host URL (env: CIRCLECI_CLI_HOST, CIRCLECI_HOST, or CIRCLE_URL)

.PP
\fB--source-token\fP=""
	API token for the source org (env: CIRCLECI_SOURCE_TOKEN)

.PP
\fB--token\fP=""
	Personal API token — fallback for both orgs (env: CIRCLECI_CLI_TOKEN or CIRCLE_TOKEN)


.SH SEE ALSO
\fBcircleci-migrate-completion(1)\fP
