package terraform

// versionsTemplate is the static versions.tf content.
// It pins the CircleCI provider to v0.3.x via a ~> constraint.
const versionsTemplate = `terraform {
  required_version = ">= 1.3"

  required_providers {
    circleci = {
      # renovate: datasource=github-releases depName=CircleCI-Public/terraform-provider-circleci
      source  = "CircleCI-Public/circleci"
      version = "~> 0.3"
    }
  }
}
`

// providersTemplate is the providers.tf content.
// .Host and .OrgID are injected at generation time.
//
// Provider attribute reference (CircleCI-Public/circleci v0.3.x, schema-verified):
//
//	key          (Optional, String, Sensitive) — CircleCI API token; falls back to
//	             CIRCLECI_TOKEN env var when omitted.
//	host         (Optional, String) — CircleCI host URL; falls back to
//	             CIRCLE_HOST env var.
//	runner_host  (Optional, String) — runner API host (optional).
//
// NOTE: there is no top-level `organization` argument on the provider block.
// The org UUID is supplied per-resource via `organization_id`.
const providersTemplate = `# Provider configuration generated by circleci-migrate terraform generate.
# The host value is set from --host (default: https://circleci.com).
# Set the API token for the destination org before running terraform apply:
#   export CIRCLECI_TOKEN="<your-personal-api-token>"
provider "circleci" {
  # key reads from CIRCLECI_TOKEN when not set explicitly.
  # See: https://registry.terraform.io/providers/CircleCI-Public/circleci/latest/docs
  host = "{{.Host}}"
}

# The destination organisation UUID is used as a local so each resource can
# reference it without duplicating the value.
locals {
  org_id = "{{.OrgID}}"
}
`

// contextsTemplate is the static contexts.tf content.
// Resources iterate over the var.contexts list (populated from migration.auto.tfvars.json).
//
// Provider attribute reference (CircleCI-Public/circleci v0.3.x, schema-verified):
//
//	circleci_context:
//	  name            (Required, String) — The context name.
//	  organization_id (Required, String) — The org UUID.
//	circleci_context_environment_variable:
//	  context_id (Required, String) — The context's ID (from circleci_context).
//	  name       (Required, String) — The env-var name.
//	  value      (Required, String, Sensitive) — The env-var value.
const contextsTemplate = `# Contexts — generated by circleci-migrate terraform generate.
#
# var.contexts is a list of objects, each with:
#   name    : context name
#   env_vars: list of env-var name strings
#
# Secrets (values) are supplied via secrets.auto.tfvars.json.

variable "contexts" {
  description = "List of CircleCI contexts to create."
  type = list(object({
    name     = string
    env_vars = optional(list(string), [])
  }))
  default = []
}

variable "context_secrets" {
  description = "Map of context name -> (map of env-var name -> value). Marked sensitive."
  type        = map(map(string))
  default     = {}
  sensitive   = true
}

# Create each context.
resource "circleci_context" "contexts" {
  for_each        = { for c in var.contexts : c.name => c }
  name            = each.value.name
  organization_id = local.org_id
}

# Create each env-var within its context.
# The key is "<context_name>/<var_name>" so each env-var is a unique resource.
locals {
  context_env_vars = flatten([
    for c in var.contexts : [
      for v in c.env_vars : {
        context_name = c.name
        var_name     = v
      }
    ]
  ])
}

resource "circleci_context_environment_variable" "context_vars" {
  for_each   = { for ev in local.context_env_vars : "${ev.context_name}/${ev.var_name}" => ev }
  context_id = circleci_context.contexts[each.value.context_name].id
  name       = each.value.var_name
  value      = try(var.context_secrets[each.value.context_name][each.value.var_name], "")
}
`

// projectsTemplate is the static projects.tf content.
// Resources iterate over the var.projects list (populated from migration.auto.tfvars.json).
//
// Provider attribute reference (CircleCI-Public/circleci v0.3.x, schema-verified):
//
//	circleci_project — flat resource (no nested block), all optional booleans:
//	  name                        (Required, String)       — Repository name.
//	  organization_id             (Required, String)       — The org UUID.
//	  auto_cancel_builds          (Optional, Bool)         — Cancel superseded builds.
//	  build_fork_prs              (Optional, Bool)         — Build fork pull requests.
//	  disable_ssh                 (Optional, Bool)         — Disable SSH access.
//	  forks_receive_secret_env_vars (Optional, Bool)       — Allow forks to receive secret env vars.
//	  set_github_status           (Optional, Bool)         — Set commit status.
//	  setup_workflows             (Optional, Bool)         — Enable setup workflows.
//	  write_settings_requires_admin (Optional, Bool)       — Require admin to write settings.
//	  pr_only_branch_overrides    (Optional, List(String)) — Branch overrides for PR-only mode.
//
//	  NOTE: The manifest's `autocancel_builds` maps to `auto_cancel_builds` (provider name).
//	  NOTE: The manifest's `oss` has no provider attribute; it is omitted.
//	  NOTE: The manifest's `build_prs_only` has no boolean attribute; use pr_only_branch_overrides instead.
//
//	circleci_project_environment_variable:
//	  project_slug (Required, String)       — The project slug (e.g. "gh/org/repo").
//	  name         (Required, String)       — The env-var name.
//	  value        (Required, String, Sensitive) — The env-var value.
//
//	NOTE: circleci_project_environment_variable uses project_slug (not project_id).
const projectsTemplate = `# Projects — generated by circleci-migrate terraform generate.
#
# var.projects is a list of objects, each with:
#   repo_name         : the repository name (VCS repo name)
#   dest_slug         : the full destination project slug (e.g. "gh/org/repo")
#   advanced_settings : optional map of bool-valued advanced settings
#   env_vars          : list of env-var name strings
#
# Secrets (values) are supplied via secrets.auto.tfvars.json.

variable "projects" {
  description = "List of CircleCI projects to create."
  type = list(object({
    repo_name         = string
    dest_slug         = string
    advanced_settings = optional(map(bool), {})
    env_vars          = optional(list(string), [])
  }))
  default = []
}

variable "project_secrets" {
  description = "Map of repo name -> (map of env-var name -> value). Marked sensitive."
  type        = map(map(string))
  default     = {}
  sensitive   = true
}

# Create each project.
resource "circleci_project" "projects" {
  for_each        = { for p in var.projects : p.repo_name => p }
  name            = each.value.repo_name
  organization_id = local.org_id

  # Optional boolean advanced settings — only emitted when present in the manifest.
  auto_cancel_builds            = try(each.value.advanced_settings["auto_cancel_builds"], null)
  build_fork_prs                = try(each.value.advanced_settings["build_fork_prs"], null)
  disable_ssh                   = try(each.value.advanced_settings["disable_ssh"], null)
  forks_receive_secret_env_vars = try(each.value.advanced_settings["forks_receive_secret_env_vars"], null)
  set_github_status             = try(each.value.advanced_settings["set_github_status"], null)
  setup_workflows               = try(each.value.advanced_settings["setup_workflows"], null)
  write_settings_requires_admin = try(each.value.advanced_settings["write_settings_requires_admin"], null)
}

# Create each env-var within its project.
# circleci_project_environment_variable uses project_slug (not project_id).
locals {
  project_env_vars = flatten([
    for p in var.projects : [
      for v in p.env_vars : {
        repo_name = p.repo_name
        dest_slug = p.dest_slug
        var_name  = v
      }
    ]
  ])
}

resource "circleci_project_environment_variable" "project_vars" {
  for_each     = { for ev in local.project_env_vars : "${ev.repo_name}/${ev.var_name}" => ev }
  project_slug = each.value.dest_slug
  name         = each.value.var_name
  value        = try(var.project_secrets[each.value.repo_name][each.value.var_name], "")
}
`
