package terraform

// versionsTemplate is the static versions.tf content.
// It pins the CircleCI provider to v0.3.x via a ~> constraint.
const versionsTemplate = `terraform {
  required_version = ">= 1.5"

  required_providers {
    circleci = {
      # renovate: datasource=github-releases depName=CircleCI-Public/terraform-provider-circleci
      source  = "CircleCI-Public/circleci"
      version = "~> 0.3"
    }
  }
}
`

// providersTemplate is the providers.tf content.
// .Host and .OrgID are injected at generation time.
//
// Provider attribute reference (CircleCI-Public/circleci v0.3.x, schema-verified):
//
//	key          (Optional, String, Sensitive) — CircleCI API token; falls back to
//	             CIRCLECI_TOKEN env var when omitted.
//	host         (Optional, String) — CircleCI host URL; falls back to
//	             CIRCLE_HOST env var.
//	runner_host  (Optional, String) — runner API host (optional).
//
// NOTE: there is no top-level `organization` argument on the provider block.
// The org UUID is supplied per-resource via `organization_id`.
const providersTemplate = `# Provider configuration generated by circleci-migrate terraform generate.
# The host value is set from --host (default: https://circleci.com).
# Set the API token for the destination org before running terraform apply:
#   export CIRCLECI_TOKEN="<your-personal-api-token>"
provider "circleci" {
  # key reads from CIRCLECI_TOKEN when not set explicitly.
  # See: https://registry.terraform.io/providers/CircleCI-Public/circleci/latest/docs
  host = "{{.Host}}"
}

# The destination organisation UUID is used as a local so each resource can
# reference it without duplicating the value.
locals {
  org_id = "{{.OrgID}}"
}
`

// contextsTemplate is the static contexts.tf content.
// Resources iterate over the var.contexts list (populated from migration.auto.tfvars.json).
//
// Provider attribute reference (CircleCI-Public/circleci v0.3.x, schema-verified):
//
//	circleci_context:
//	  name            (Required, String) — The context name.
//	  organization_id (Required, String) — The org UUID.
//	circleci_context_environment_variable:
//	  context_id (Required, String) — The context's ID (from circleci_context).
//	  name       (Required, String) — The env-var name.
//	  value      (Required, String, Sensitive) — The env-var value.
const contextsTemplate = `# Contexts — generated by circleci-migrate terraform generate.
#
# var.contexts is a list of objects, each with:
#   name    : context name
#   env_vars: list of env-var name strings
#
# Secrets (values) are supplied via secrets.auto.tfvars.json.

variable "contexts" {
  description = "List of CircleCI contexts to create."
  type = list(object({
    name     = string
    env_vars = optional(list(string), [])
  }))
  default = []
}

variable "context_secrets" {
  description = "Map of context name -> (map of env-var name -> value). Marked sensitive."
  type        = map(map(string))
  default     = {}
  sensitive   = true
}

# Create each context.
resource "circleci_context" "contexts" {
  for_each        = { for c in var.contexts : c.name => c }
  name            = each.value.name
  organization_id = local.org_id
}

# Create each env-var within its context.
# The key is "<context_name>/<var_name>" so each env-var is a unique resource.
locals {
  context_env_vars = flatten([
    for c in var.contexts : [
      for v in c.env_vars : {
        context_name = c.name
        var_name     = v
      }
    ]
  ])
}

resource "circleci_context_environment_variable" "context_vars" {
  for_each   = { for ev in local.context_env_vars : "${ev.context_name}/${ev.var_name}" => ev }
  context_id = circleci_context.contexts[each.value.context_name].id
  name       = each.value.var_name
  value      = try(var.context_secrets[each.value.context_name][each.value.var_name], "")
}
`

// projectsTemplate is the projects.tf content for STANDALONE destination orgs.
// Standalone orgs (GitHub App / GitLab / circleci-type) support all
// circleci_project advanced-settings attributes.
//
// Provider attribute reference (CircleCI-Public/circleci v0.3.x, schema-verified):
//
//	circleci_project — flat resource (no nested block), all optional booleans:
//	  name                        (Required, String)       — Repository name.
//	  organization_id             (Required, String)       — The org UUID.
//	  auto_cancel_builds          (Optional, Bool)         — Cancel superseded builds.
//	  build_fork_prs              (Optional, Bool)         — Build fork pull requests.
//	  disable_ssh                 (Optional, Bool)         — Disable SSH access.
//	  forks_receive_secret_env_vars (Optional, Bool)       — Allow forks to receive secret env vars.
//	  set_github_status           (Optional, Bool)         — Set commit status.
//	  setup_workflows             (Optional, Bool)         — Enable setup workflows.
//	  write_settings_requires_admin (Optional, Bool)       — Require admin to write settings.
//	  pr_only_branch_overrides    (Optional, List(String)) — Branch overrides for PR-only mode.
//	  slug                        (Computed, String)       — The project slug (e.g. "circleci/<org>/<proj>").
//
//	  NOTE: The manifest's `autocancel_builds` maps to `auto_cancel_builds` (provider name).
//	  NOTE: The manifest's `oss` has no provider attribute; it is omitted.
//	  NOTE: The manifest's `build_prs_only` has no boolean attribute; use pr_only_branch_overrides instead.
//
//	circleci_project_environment_variable:
//	  project_slug (Required, String)       — The project slug (e.g. "gh/org/repo").
//	  name         (Required, String)       — The env-var name.
//	  value        (Required, String, Sensitive) — The env-var value.
//
//	NOTE: project_slug is referenced from the created project resource (.slug output)
//	so the correct format is used regardless of org type.
const projectsTemplate = `# Projects — generated by circleci-migrate terraform generate.
# Destination org type: standalone (GitHub App / GitLab / circleci-type).
# Advanced project settings ARE included (GetSettings/UpdateSettings supported).
#
# var.projects is a list of objects, each with:
#   repo_name         : the repository name (VCS repo name)
#   dest_slug         : the full destination project slug (e.g. "circleci/org/repo")
#   advanced_settings : optional map of bool-valued advanced settings
#   env_vars          : list of env-var name strings
#
# Secrets (values) are supplied via secrets.auto.tfvars.json.

variable "projects" {
  description = "List of CircleCI projects to create."
  type = list(object({
    repo_name         = string
    dest_slug         = string
    advanced_settings = optional(map(bool), {})
    env_vars          = optional(list(string), [])
  }))
  default = []
}

variable "project_secrets" {
  description = "Map of repo name -> (map of env-var name -> value). Marked sensitive."
  type        = map(map(string))
  default     = {}
  sensitive   = true
}

# Create each project.
resource "circleci_project" "projects" {
  for_each        = { for p in var.projects : p.repo_name => p }
  name            = each.value.repo_name
  organization_id = local.org_id

  # Optional boolean advanced settings — only emitted when present in the manifest.
  # These attributes are only supported for standalone (GitHub App / GitLab) orgs.
  auto_cancel_builds            = try(each.value.advanced_settings["auto_cancel_builds"], null)
  build_fork_prs                = try(each.value.advanced_settings["build_fork_prs"], null)
  disable_ssh                   = try(each.value.advanced_settings["disable_ssh"], null)
  forks_receive_secret_env_vars = try(each.value.advanced_settings["forks_receive_secret_env_vars"], null)
  set_github_status             = try(each.value.advanced_settings["set_github_status"], null)
  setup_workflows               = try(each.value.advanced_settings["setup_workflows"], null)
  write_settings_requires_admin = try(each.value.advanced_settings["write_settings_requires_admin"], null)
}

# Create each env-var within its project.
# project_slug is taken from the created circleci_project resource (.slug) so
# the correct slug format is used for the destination org type automatically.
locals {
  project_env_vars = flatten([
    for p in var.projects : [
      for v in p.env_vars : {
        repo_name = p.repo_name
        var_name  = v
      }
    ]
  ])
}

resource "circleci_project_environment_variable" "project_vars" {
  for_each     = { for ev in local.project_env_vars : "${ev.repo_name}/${ev.var_name}" => ev }
  project_slug = circleci_project.projects[each.value.repo_name].slug
  name         = each.value.var_name
  value        = try(var.project_secrets[each.value.repo_name][each.value.var_name], "")
}
`

// projectsOAuthTemplate is the projects.tf content for OAUTH destination orgs.
// OAuth orgs (GitHub OAuth, "gh/" slug prefix) do NOT support the
// circleci_project advanced-settings attributes (GetSettings/UpdateSettings is
// standalone-only). Emitting those attributes would cause terraform apply to
// fail. Advanced settings must be configured via the CircleCI UI or CLI sync.
const projectsOAuthTemplate = `# Projects — generated by circleci-migrate terraform generate.
# Destination org type: oauth (GitHub OAuth / "gh/" slug prefix).
#
# NOTE: Advanced project settings (auto_cancel_builds, build_fork_prs,
# disable_ssh, forks_receive_secret_env_vars, set_github_status,
# setup_workflows, write_settings_requires_admin) are NOT included here.
# The CircleCI Terraform provider's GetSettings/UpdateSettings is only
# available for standalone (GitHub App / GitLab) orgs. For OAuth orgs,
# configure project settings via the CircleCI UI or with:
#   circleci-migrate sync --manifest manifest.json --dest-token $CIRCLECI_DEST_TOKEN --apply
#
# var.projects is a list of objects, each with:
#   repo_name : the repository name (VCS repo name)
#   dest_slug : the full destination project slug (e.g. "gh/org/repo")
#   env_vars  : list of env-var name strings
#
# Secrets (values) are supplied via secrets.auto.tfvars.json.

variable "projects" {
  description = "List of CircleCI projects to create."
  type = list(object({
    repo_name = string
    dest_slug = string
    env_vars  = optional(list(string), [])
  }))
  default = []
}

variable "project_secrets" {
  description = "Map of repo name -> (map of env-var name -> value). Marked sensitive."
  type        = map(map(string))
  default     = {}
  sensitive   = true
}

# Create each project.
# Advanced settings are managed via the CircleCI UI for OAuth orgs.
resource "circleci_project" "projects" {
  for_each        = { for p in var.projects : p.repo_name => p }
  name            = each.value.repo_name
  organization_id = local.org_id
}

# Create each env-var within its project.
# project_slug is taken from the created circleci_project resource (.slug) so
# the correct slug format is used for the destination org type automatically.
locals {
  project_env_vars = flatten([
    for p in var.projects : [
      for v in p.env_vars : {
        repo_name = p.repo_name
        var_name  = v
      }
    ]
  ])
}

resource "circleci_project_environment_variable" "project_vars" {
  for_each     = { for ev in local.project_env_vars : "${ev.repo_name}/${ev.var_name}" => ev }
  project_slug = circleci_project.projects[each.value.repo_name].slug
  name         = each.value.var_name
  value        = try(var.project_secrets[each.value.repo_name][each.value.var_name], "")
}
`

// restrictionsTemplate is the restrictions.tf content.
// Context restrictions are emitted for both org types, with the following gating:
//   - type=project: both org types
//   - type=expression: both org types
//   - type=group: OAuth ONLY (provider rejects on standalone orgs)
//
// Provider attribute reference (CircleCI-Public/circleci v0.3.x, schema-verified):
//
//	circleci_context_restriction:
//	  context_id (Required, String) — The context UUID (from circleci_context.id).
//	  type       (Required, String) — "project" | "expression" | "group".
//	  value      (Required, String) — Project UUID, expression string, or group UUID.
//	                                  For project restrictions, use the destination
//	                                  project's UUID (circleci_project.projects[...].id).
//
// NOTE: For project restrictions, value must be the DESTINATION project UUID.
// The HCL below uses var.project_repo_name to look up the circleci_project resource
// and obtain its .id, eliminating the need to remap source→destination project UUIDs.
// Each project restriction carries an additional project_repo_name field so the
// lookup can be done per-restriction.
//
// NOTE: For expression restrictions, the value is an expression string such as
// `project.slug == "gh/org/repo"` — these may reference source-org slugs that
// need updating after migration. Review expression values before applying.
const restrictionsTemplate = `# Context restrictions — generated by circleci-migrate terraform generate.
#
# var.restrictions is a list of objects, each with:
#   context_name      : name of the parent context
#   type              : "project" | "expression" | "group"
#   value             : project UUID (for project) / expression string / group UUID
#   project_repo_name : repo name of the project (for project restrictions only;
#                       used to look up circleci_project.projects[...].id)
#
# NOTE: For project restrictions, value is set to the destination project's UUID
# via circleci_project.projects[project_repo_name].id.
# This reference is only valid when project_repo_name is non-empty and the project
# is present in var.projects.
#
# NOTE: For expression restrictions, the value string may reference source-org
# slugs (e.g. "project.slug == \"gh/acme/api\""). Update those expressions to
# match the destination org slug after the migration.
#
# NOTE: Group restrictions (type=group) are only supported for GitHub OAuth
# destination orgs. For standalone (GitHub App / GitLab) orgs they are omitted.
# Group UUIDs are VCS-team-specific and may differ in the destination org.

variable "restrictions" {
  description = "List of context restrictions to create."
  type = list(object({
    context_name      = string
    type              = string
    value             = string
    project_repo_name = optional(string, "")
  }))
  default = []
}

resource "circleci_context_restriction" "restrictions" {
  for_each = {
    for r in var.restrictions :
    "${r.context_name}/${r.type}/${r.value}" => r
  }

  context_id = circleci_context.contexts[each.value.context_name].id
  type       = each.value.type
  # For project restrictions: resolve the destination project UUID from the
  # circleci_project resource using project_repo_name.
  # For expression/group restrictions: use the value as-is.
  value = (
    each.value.type == "project" && each.value.project_repo_name != ""
    ? circleci_project.projects[each.value.project_repo_name].id
    : each.value.value
  )
}
`

// webhooksTemplate is the webhooks.tf content.
// Webhooks are supported on both org types.
//
// Provider attribute reference (CircleCI-Public/circleci v0.3.x, schema-verified):
//
//	circleci_webhook:
//	  name           (Required, String)          — Webhook name.
//	  url            (Required, String)           — Webhook endpoint URL.
//	  events         (Required, List(String))     — Events that trigger this webhook
//	                                                 (e.g. "workflow-completed", "job-completed").
//	  verify_tls     (Optional, Bool)             — Verify TLS certificate. Default: true.
//	  scope_id       (Required, String)           — Destination project UUID
//	                                                 (from circleci_project.projects[...].id).
//	  scope_type     (Required, String)           — Scope type; always "project".
//	  signing_secret (Required, String, Sensitive) — Signing secret for payload verification.
//	                                                 Must be provided; the server uses it to
//	                                                 sign payloads but does not auto-generate it.
//
// NOTE: scope_id uses the destination project UUID from the created
// circleci_project resource — no hard-coded UUID needed.
const webhooksTemplate = `# Webhooks — generated by circleci-migrate terraform generate.
# Both OAuth and standalone destination orgs are supported.
#
# var.webhooks is a list of objects, each with:
#   project_repo_name : the repository name of the parent project
#   name              : webhook name
#   url               : webhook endpoint URL
#   events            : list of event type strings
#   verify_tls        : whether to verify TLS (default: true)
#   signing_secret    : secret used to sign webhook payloads (required by provider;
#                       replace placeholder with: openssl rand -hex 32)
#
# NOTE: Webhook URLs are written as-is from the manifest. Verify that these
# endpoints are accessible from the destination CircleCI org before applying.
# signing_secret is REQUIRED by the provider. Set a strong random value (e.g. 32 hex chars);
# the same value must be configured in the webhook consumer to verify payloads.
# Replace the default placeholder with: openssl rand -hex 32

variable "webhooks" {
  description = "List of project webhooks to create."
  type = list(object({
    project_repo_name = string
    name              = string
    url               = string
    events            = list(string)
    verify_tls        = optional(bool, true)
    signing_secret    = optional(string, "REPLACE_ME_SIGNING_SECRET")
  }))
  default = []
}

resource "circleci_webhook" "webhooks" {
  for_each = {
    for w in var.webhooks :
    "${w.project_repo_name}/${w.name}" => w
  }
  name           = each.value.name
  url            = each.value.url
  events         = each.value.events
  verify_tls     = each.value.verify_tls
  scope_id       = circleci_project.projects[each.value.project_repo_name].id
  scope_type     = "project"
  signing_secret = each.value.signing_secret
}
`

// runnersTemplate is the runners.tf content.
// Self-hosted runner resource classes and tokens are supported on both org types.
//
// Provider attribute reference (CircleCI-Public/circleci v0.3.x, schema-verified):
//
//	circleci_runner_resource_class:
//	  organization_id (Required, String)  — The org UUID.
//	  resource_class  (Required, String)  — The full resource class name ("namespace/class").
//	  description     (Optional, String)  — Human-readable description.
//	  id              (Computed, String)  — Server-assigned UUID.
//
//	circleci_runner_token:
//	  organization_id (Required, String)  — The org UUID.
//	  resource_class  (Required, String)  — The resource class name this token authenticates.
//	  nickname        (Required, String)  — Human-readable token nickname.
//	  token           (Computed, String, Sensitive) — The runner token value (server-generated).
//
// NOTE: Runner tokens are server-generated and written once. Save them
// before terraform destroy, or you will need to recreate them.
// NOTE: resource_class must match an existing class — it references the
// circleci_runner_resource_class.runners[...].resource_class computed output.
const runnersTemplate = `# Self-hosted runner resource classes and tokens
# Generated by circleci-migrate terraform generate.
# Both OAuth and standalone destination orgs are supported.
#
# var.runner_classes is a list of objects, each with:
#   resource_class : full resource class name ("namespace/class-name")
#   description    : optional human-readable description
#
# NOTE: Runner tokens are server-generated after creation and cannot be
# retrieved again — save the outputs of 'terraform apply' before proceeding.
# NOTE: The runner namespace must already exist in the destination org.

variable "runner_classes" {
  description = "List of self-hosted runner resource classes to create."
  type = list(object({
    resource_class = string
    description    = optional(string, "")
  }))
  default = []
}

resource "circleci_runner_resource_class" "runners" {
  for_each        = { for rc in var.runner_classes : rc.resource_class => rc }
  organization_id = local.org_id
  resource_class  = each.value.resource_class
  description     = each.value.description
}

# Each resource class gets one runner token with a standard nickname.
# Override nicknames by adding a nickname field to var.runner_classes and
# referencing each.value.nickname below.
resource "circleci_runner_token" "runner_tokens" {
  for_each        = { for rc in var.runner_classes : rc.resource_class => rc }
  organization_id = local.org_id
  resource_class  = circleci_runner_resource_class.runners[each.key].resource_class
  nickname        = "${each.key}-token"
}
`

// pipelinesTemplate is the pipelines.tf content.
// Pipeline definitions and triggers are only supported for standalone
// (GitHub App / GitLab) destination orgs. For OAuth orgs, this file is
// NOT generated (the provider schema rejects github_oauth).
//
// Provider attribute reference (CircleCI-Public/circleci v0.3.x, schema-verified
// against v0.3.8 via `terraform providers schema -json`):
//
//	circleci_pipeline (all FLAT top-level attributes, NO nested blocks):
//	  name                             (Required, String)  — Pipeline definition name.
//	  description                      (Required, String)  — Human-readable description.
//	  project_id                       (Required, String)  — Project UUID (circleci_project.id).
//	  config_source_provider           (Required, String)  — "github_app" | "github_server".
//	  config_source_repo_external_id   (Required, String)  — GitHub repo numeric ID.
//	  config_source_file_path          (Required, String)  — Config file path.
//	  checkout_source_provider         (Required, String)  — "github_app" | "github_server".
//	  checkout_source_repo_external_id (Required, String)  — GitHub repo numeric ID.
//
//	circleci_trigger (all FLAT top-level attributes, NO nested blocks, NO name attr):
//	  pipeline_id                           (Required, String)  — Pipeline def UUID.
//	  project_id                            (Required, String)  — Project UUID.
//	  event_preset                          (Optional, String)  — e.g. "all-pushes".
//	  disabled                              (Optional, Bool)    — Whether disabled.
//	  event_source_provider                 (Required, String)  — "github_app"|"github_server"|"webhook"|"schedule".
//	  event_source_repo_external_id         (Optional, String)  — GitHub repo numeric ID.
//	  event_source_schedule_cron_expression (Optional, String)  — Cron expression (schedule only).
const pipelinesTemplate = `# Pipeline definitions and triggers — generated by circleci-migrate terraform generate.
# Destination org type: standalone (GitHub App / GitLab / circleci-type) ONLY.
#
# IMPORTANT: This file is NOT generated for OAuth (gh/) destination orgs
# because the CircleCI Terraform provider rejects github_oauth for these
# resource types. See GAPS.md for the OAuth gap note.
#
# Provider attribute reference (CircleCI-Public/circleci v0.3.x, schema-verified):
#   circleci_pipeline uses FLAT top-level attributes (no nested blocks):
#     config_source_provider, config_source_repo_external_id, config_source_file_path,
#     checkout_source_provider, checkout_source_repo_external_id
#   circleci_trigger uses FLAT top-level attributes (no nested blocks, no name attr):
#     event_source_provider, event_source_repo_external_id,
#     event_source_schedule_cron_expression
#
# var.pipelines is a list of objects, each with:
#   project_repo_name              : repository name of the parent project
#   name                           : pipeline definition name
#   description                    : optional description
#   config_source_provider         : "github_app" | "github_server"
#   config_source_repo_external_id : GitHub repo numeric ID (string)
#   config_source_file_path        : path to config file (e.g. ".circleci/config.yml")
#   checkout_source_provider       : "github_app" | "github_server"
#   checkout_source_repo_external_id : GitHub repo numeric ID (string)
#   triggers                       : list of trigger objects

variable "pipelines" {
  description = "List of pipeline definitions to create (standalone orgs only)."
  type = list(object({
    project_repo_name                = string
    name                             = string
    description                      = optional(string, "")
    config_source_provider           = string
    config_source_repo_external_id   = string
    config_source_file_path          = optional(string, ".circleci/config.yml")
    checkout_source_provider         = string
    checkout_source_repo_external_id = string
    triggers = optional(list(object({
      event_preset                          = optional(string, "")
      event_source_provider                 = string
      event_source_repo_external_id         = optional(string, "")
      event_source_schedule_cron_expression = optional(string, "")
      disabled                              = optional(bool, false)
    })), [])
  }))
  default = []
}

# Create each pipeline definition.
# All source attributes are flat (no nested blocks) — schema-verified against
# CircleCI-Public/circleci v0.3.8.
resource "circleci_pipeline" "pipelines" {
  for_each                         = { for p in var.pipelines : "${p.project_repo_name}/${p.name}" => p }
  name                             = each.value.name
  description                      = each.value.description
  project_id                       = circleci_project.projects[each.value.project_repo_name].id
  config_source_provider           = each.value.config_source_provider
  config_source_repo_external_id   = each.value.config_source_repo_external_id
  config_source_file_path          = each.value.config_source_file_path
  checkout_source_provider         = each.value.checkout_source_provider
  checkout_source_repo_external_id = each.value.checkout_source_repo_external_id
}

# Create each trigger — flattened from the nested triggers list.
# NOTE: circleci_trigger has no "name" attribute in the provider schema.
# Triggers are identified by their position/event configuration.
locals {
  pipeline_triggers = flatten([
    for p in var.pipelines : [
      for idx, t in p.triggers : {
        pipeline_key                          = "${p.project_repo_name}/${p.name}"
        project_repo_name                     = p.project_repo_name
        trigger_index                         = idx
        event_preset                          = t.event_preset
        event_source_provider                 = t.event_source_provider
        event_source_repo_external_id         = t.event_source_repo_external_id
        event_source_schedule_cron_expression = t.event_source_schedule_cron_expression
        disabled                              = t.disabled
      }
    ]
  ])
}

resource "circleci_trigger" "triggers" {
  for_each = {
    for t in local.pipeline_triggers :
    "${t.pipeline_key}/${t.trigger_index}" => t
  }
  pipeline_id                           = circleci_pipeline.pipelines[each.value.pipeline_key].id
  project_id                            = circleci_project.projects[each.value.project_repo_name].id
  event_preset                          = each.value.event_preset != "" ? each.value.event_preset : null
  disabled                              = each.value.disabled
  event_source_provider                 = each.value.event_source_provider
  event_source_repo_external_id         = each.value.event_source_provider == "github_app" || each.value.event_source_provider == "github_server" ? each.value.event_source_repo_external_id : null
  event_source_schedule_cron_expression = each.value.event_source_provider == "schedule" ? each.value.event_source_schedule_cron_expression : null
}
`
