package cmd

// bundleEncryptCmd is a hidden internal command used by the inline CircleCI
// pipeline config to encrypt a JSON file in place using age.
//
// Usage (in-pipeline only):
//
//	circleci-migrate bundle-encrypt --recipient <pubkey> --input <file> --output <file>
//
// The command reads the plaintext JSON from --input, encrypts it with age
// using the supplied recipient public key (ssh-ed25519/ssh-rsa/age1...),
// and writes the binary age ciphertext to --output.
//
// SECURITY: the public key (recipient) is safe to embed in the pipeline
// config. Private keys / plaintext values are never logged.

import (
	"fmt"
	"os"
	"strings"

	bundlepkg "github.com/AwesomeCICD/circleci-org-migration-cli/internal/bundle"
	"github.com/spf13/cobra"
)

func newBundleEncryptCommand() *cobra.Command {
	var (
		recipient  string
		inputFile  string
		outputFile string
	)

	cmd := &cobra.Command{
		Use:    "bundle-encrypt --recipient <pubkey> --input <in> --output <out>",
		Short:  "Encrypt a JSON bundle file with age (internal/pipeline use).",
		Hidden: true, // not shown in --help; used by inline pipeline config
		Long: `bundle-encrypt is an internal command called by the inline pipeline config
generated by 'secrets capture --encrypt'. It reads a plaintext JSON file,
encrypts it with age using the provided recipient public key, and writes the
binary age ciphertext to the output file.

SECURITY: The recipient is a PUBLIC key — safe to embed in pipeline configs.
The plaintext is held in memory only and is never logged.`,
		Args: cobra.NoArgs,
		RunE: func(_ *cobra.Command, _ []string) error {
			if recipient == "" {
				return fmt.Errorf("--recipient is required")
			}
			if inputFile == "" {
				return fmt.Errorf("--input is required")
			}
			if outputFile == "" {
				return fmt.Errorf("--output is required")
			}

			// Read plaintext. Do NOT log.
			plaintext, err := os.ReadFile(inputFile)
			if err != nil {
				return fmt.Errorf("reading input %s: %w", inputFile, err)
			}

			// Parse public key recipient. SECURITY: do not log the key string.
			r, err := bundlepkg.ParseRecipient(strings.TrimSpace(recipient))
			if err != nil {
				return fmt.Errorf("parsing recipient: %w", err)
			}

			ciphertext, err := bundlepkg.EncryptBundle(plaintext, r)
			if err != nil {
				return fmt.Errorf("encrypting bundle: %w", err)
			}

			// #nosec G703 -- outputFile is an operator-provided path on their own machine (local CLI), not attacker-controlled.
			if err := os.WriteFile(outputFile, ciphertext, 0o600); err != nil {
				return fmt.Errorf("writing encrypted output to %s: %w", outputFile, err)
			}

			fmt.Fprintf(os.Stderr, "bundle-encrypt: wrote %d bytes to %s\n", len(ciphertext), outputFile)
			return nil
		},
	}

	f := cmd.Flags()
	f.StringVar(&recipient, "recipient", "",
		"age or SSH public key recipient string (ssh-ed25519/ssh-rsa/age1...)")
	f.StringVar(&inputFile, "input", "",
		"Path to the plaintext JSON file to encrypt")
	f.StringVar(&outputFile, "output", "",
		"Path to write the encrypted output (.age)")
	return cmd
}
